name: 'Setup BOMnipotent Client'
description: |-
      Downloads and caches BOMnipotent Client, and adds it to the PATH.
author: 'Weichwerke Heidrich Software'
inputs:
  domain:
    description: |-
      Specify the domain of the BOMnipotent Server to be stored. It can be overridden by command line arguments in later calls.
    required: false
    default: ''
  user:
    description: |-
      Specify the username of a robot user registered at the BOMnipotent Server you are targeting.
    required: false
    default: ''
  secret-key:
    description: |-
      Specify the secret key of the robot user registered at the BOMnipotent Server you are targeting.
      This is used to authenticate the robot user with the BOMnipotent Server.
      Make it available to your pipeline via <your repo> → Settings → Secrets and variables → Actions → New repository secret.
    required: false
    default: ''
  log-level:
    description: |-
      Specify the log level on which BOMnipotent Client communicates with you. Valid values are 'error', 'warn', 'info' (default), 'debug' and 'trace'.
    required: false
    default: ''
  verify-session:
    description: |-
      If set to false, this skips the verification that the entered session data is valid.
    required: false
    default: 'true'
  version:
    description: |-
      Specify the version of BOMnipotent Client to download. If not specified, the latest version will be used.
    required: false
    default: 'latest'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'triangle'
  color: 'orange'
