on: [push]

jobs:
  test-action:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    name: Running the BOMnipotent Client setup action
    steps:
      - name: Setup latest version of BOMnipotent Client
        id: setup-latest
        uses: Weichwerke-Heidrich-Software/setup-bomnipotent-action@v1

      - name: Display the latest BOMnipotent Client version
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            bomnipotent_client.exe --version
          else
            bomnipotent_client --version
          fi
        shell: bash

      - name: Setup specific version of BOMnipotent Client
        id: setup-specific
        uses: Weichwerke-Heidrich-Software/setup-bomnipotent-action@v1
        with:
          version: '0.4.2'

      - name: Display the specific BOMnipotent Client version
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            bomnipotent_client.exe --version
          else
            bomnipotent_client --version
          fi
        shell: bash
