on: [push]

jobs:
  test-action:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    name: Running the BOMnipotent Client setup action
    steps:
      - name: Setup latest version of BOMnipotent Client and store session data
        id: setup-latest
        uses: Weichwerke-Heidrich-Software/setup-bomnipotent-action@v1
        with:
          domain: 'https://bomnipotent.wwh-soft.com'
          user: 'wwh_soft_robot'
          secret-key: ${{ secrets.CLIENT_SECRET_KEY }}
          log-level: 'debug'

      - name: Display the session data
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            bomnipotent_client.exe session status
          else
            bomnipotent_client session status
          fi
        shell: bash

      - name: Setup specific version of BOMnipotent Client
        id: setup-specific
        uses: Weichwerke-Heidrich-Software/setup-bomnipotent-action@v1
        with:
          version: '0.4.2'
          verify-session: 'false'

      - name: Display the BOMnipotent Client version
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            bomnipotent_client.exe --version
          else
            bomnipotent_client --version
          fi
        shell: bash
